name: Python Test

on:
  workflow_dispatch:

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with: 
          python-version: '3.9'
          architecture: 'x64'
          
      - name: Install PyTest
        run: pip install pytest

      - name: Run python test math-function
        run: pytest.exe function.py
