name: Python Test

on:
  workflow_dispatch:

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with: 
          python-version: '3.9'
          
      - name: Upgrade PIP
        run: python -m pip install --upgrade pip
        
      - name: Install PyTest
        run: pip install pytest
        
      - name: Install Coverage
        run: pip install coverage
        
      - name: Coverage test math-function
        run: coverage run ./test_function.py
        
      - name: Coverage report
        run: coverage report

      - name: Test with pytest math-function
        run: pytest -vs ./test_function.py
